dimple:
  # 名称
  name: Robot
  # 版本
  version: 1.1
  # 版权年份
  copyrightYear: 2019
  # 文件路径/home/file/
  #profile: E:\
  profile: /home/file/
  # 获取ip地址开关
  addressEnabled: true
  #七牛云配置
  qiniuyun:
    accessKey: aFQMZIRzIi-MyK9ECOnAvagTLpX_tDV1ec3-iBNJ
    secretKey: IlidAClrr9Yr5u2NrJ3_mP4OD8WQhB82Bbnp7l-U
    bucket: zzlzd-image
    path: http://image.zzlzd.com
    imageMaxSize: 52428800
    imageMaxNameLength: 200
  baidu:
    clientId:
    clientSecret:
server:
  # 服务端口
  port: 80
  #port: 80
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.dimple: DEBUG
    org.springframework: DEBUG
    org.spring.springboot.dao: DEBUG

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  mail:
    host: smtp.163.com
    default-encoding: UTF-8
    username: dimple_blog@163.com
    password:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #druid
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 本地环境 172.18.56.193 63790 duoxueyimen
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.dimple.project
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: false
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*